<a href="https://colab.research.google.com/github/SnehiCodes/pytorch-practice/blob/main/introductory1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)


2.5.1+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


Creating a Tensor


In [5]:
# using empty
a = torch.empty(2,3)

In [6]:
a

tensor([[1.5766e-19, 1.0256e-08, 4.1019e-08],
        [3.0957e+12, 1.0838e-08, 1.7092e-04]])

In [7]:
# check type
type(a)

torch.Tensor

In [8]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand
torch.rand(2,3)

tensor([[0.6846, 0.8287, 0.5663],
        [0.4342, 0.0909, 0.4823]])

In [11]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways
# arange
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [16]:
# using linspace
print("using linspace ->", torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [17]:
# using eye
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [18]:
# using full
print("using full ->", torch.full((3, 3), 5))

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [20]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[      101270240, 138879389265712,               0],
        [              0,               0,               0]])

In [22]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7291666688462971446]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Data Types

In [26]:
# find data type
x.dtype

torch.int64

In [27]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [29]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

 *Mathematical operations*

1. Element wise operation