<a href="https://colab.research.google.com/github/SnehiCodes/pytorch-practice/blob/main/introductory1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)


2.5.1+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


Creating a Tensor


In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
a

tensor([[7.9421e-35, 4.4135e-41, 7.9421e-35],
        [4.4135e-41, 9.6917e-35, 0.0000e+00]])

In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.4498, 0.3033, 0.4718],
        [0.7833, 0.7834, 0.7985]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways
# arange
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [14]:
# using linspace
print("using linspace ->", torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [15]:
# using eye
print("using eye ->", torch.eye(5))

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [16]:
# using full
print("using full ->", torch.full((3, 3), 5))

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7161113971195798069]])

In [20]:
torch.empty_like(x)

tensor([[      123616072, 135269994988645,               0],
        [135269994987646,       123616104,            1126]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Data Types

In [24]:
# find data type
x.dtype

torch.int64

In [25]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

 *Mathematical operations*

1. Scalar Operation

In [28]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [29]:
# addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [30]:
# substraction
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [31]:
# multiplication
x * 3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [32]:
# division
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [33]:
# int division
(x * 100)//3

tensor([[23., 26.],
        [13., 30.]])

In [34]:
# mod
((x * 100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [35]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

***2. Element wise operation***

In [36]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [37]:
# add
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [38]:
# sub
a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [39]:
# multiply
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [40]:
# division
a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [41]:
# power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [43]:
c = torch.tensor([1, -2, 3, -4])

In [44]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [45]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [46]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [47]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [48]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [49]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [50]:
# clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.3000, 3.7000, 4.0000])

***3. Reduction operation***

In [51]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [52]:
# sum
torch.sum(e)

tensor(24.)

In [53]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 8.,  0., 16.])

In [54]:
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [55]:
# mean
torch.mean(e)

tensor(4.)

In [56]:
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [57]:
# median
torch.median(e)

tensor(0.)

In [58]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [59]:
# product
torch.prod(e)

tensor(0.)

In [60]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [61]:
# variance
torch.var(e)

tensor(19.6000)

In [62]:
# argmax
torch.argmax(e)

tensor(5)

In [64]:
# argmin
torch.argmin(e)

tensor(1)

***4. Matrix operations***

In [67]:
f = torch.randint(size=(2,3), low=0, high=16)
g = torch.randint(size=(3,2), low=0, high=16)

print(f)
print(g)

tensor([[ 2, 15,  5],
        [11,  8, 14]])
tensor([[ 1, 14],
        [ 0, 15],
        [ 7, 13]])


In [68]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 37, 318],
        [109, 456]])

In [70]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [71]:
# transpose
torch.transpose(f, 0, 1)

tensor([[ 2, 11],
        [15,  8],
        [ 5, 14]])

In [72]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 6., 4.],
        [0., 8., 4.],
        [7., 2., 3.]])

In [73]:
# determinant
torch.det(h)

tensor(-56.0000)

In [74]:
# inverse
torch.inverse(h)

tensor([[-0.2857,  0.1786,  0.1429],
        [-0.5000,  0.5000,  0.0000],
        [ 1.0000, -0.7500,  0.0000]])

***5. Comparison operations***

In [75]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 5, 6],
        [2, 9, 5]])
tensor([[0, 4, 2],
        [7, 1, 1]])


In [76]:
# greater than
i > j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [77]:
# less than
i < j

tensor([[False, False, False],
        [ True, False, False]])

In [78]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [79]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

***6. Special functions***

In [80]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [81]:
# log
torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [82]:
# exp
torch.exp(k)

tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])

In [83]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [84]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [86]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [87]:
# relu
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

***7. Inplace Operations***

In [88]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [89]:
m.add_(n)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [90]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [91]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [92]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [93]:
m.relu_()

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [94]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

***Copying a Tensor***

In [95]:
a = torch.rand(2,3)
a

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [96]:
b = a
b

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [97]:
a[0][0] = 0
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [98]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [101]:
print(id(a))
print(id(b))

135270086141872
135270086141872


In [102]:
b = a.clone()

In [103]:
print(a)
print(b)

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])


In [104]:
a[0][0] = 10
print(a)
print(b)

tensor([[10.0000,  0.0887,  0.4890],
        [ 0.5887,  0.7340,  0.8497]])
tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])


In [105]:
print(id(a))
print(id(b))

135270086141872
135269860130064
